### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by remz1337** [evoasm/evoasm#1]
Hello,

I have imported both kasm and evoasm into intellij. After adding the JUnit dependency, I was able to successfully compile all modules with a couple of warnings but no error.

After that, I tried to run all and I all 13 tests failed with errors like:

- java.lang.UnsatisfiedLinkError: no kasm_buffer in java.library.path: [/home/remz/IdeaProjects/kasm/kasm-native/lib]
- java.lang.NoClassDefFoundError: Could not initialize class evoasm.x64.Interpreter

Again, I'm probably overlooking something simple but my Java is rusty and not familiar with IntelliJ.

Also, not sure if I need those tests in order to run the examples you provide in the Readme.

Thank you in advance! Can't wait to play with this framework

**Comment by furunkel** [comment]
Looks like you forgot to compile the native library.
Did you do this?
```
$ cd kasm-native/lib
$ mkdir build
$ cd build
$ cmake ..
```

**Comment by remz1337** [comment]
Yes indeed! I had to install pkg-config, cmake-data and libcapstone-dev in order for cmake to compile the library successfully.

After that, I rebuilt all the modules and tried to run again but got the same results (all test cases failed with the same errors)

Do I have to link the lib somehow?

**Comment by furunkel** [comment]
Is `kasm_buffer.so` in `/home/remz/IdeaProjects/kasm/kasm-native/lib` ?
Are you sure it's exactly the same error?

**Comment by remz1337** [comment]
No, it's not there. It's weird because cmake runs without any error:
cmake output:
```
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP: TRUE   
-- Configuring done
-- Generating done
-- Build files have been written to: /home/remz/IdeaProjects/kasm/kasm-native/lib/build
```
I also searched in the build folder and even all other folders of the project and couldn't find the file

**Comment by furunkel** [comment]
Ugh, forgot `make` at the end which triggers the actual build, sorry.

**Comment by remz1337** [comment]
oh, true.

All tests passed. I can start playing with it.

Thank you!
